spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/mymms?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useAffectedRows=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456root
    driverClassName: com.mysql.cj.jdbc.Driver #mysql 8.*以上版本需要用此类型的驱动，并且pom依赖也需要调整为相应的MySQL版本
#    driverClassName:  com.mysql.jdbc.Driver
    druid:
      initialSize:  10
      minIdle: 10
      maxActive: 20
      maxWait: 60000
      testOnBorrow: true
      testWhileIdle: false
      testOnReturn: false
      removeAbandoned: true
      removeAbandonedTimeout: 60
      timeBetweenEvictionRunsMillis: 300000
      validationQuery:  SELECT 'x'
      maxPoolPreparedStatementPerConnectionSize: 20
      minEvictableIdleTimeMillis: 300000
      filters: stat,wall
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=100
