spring:
  cloud:
    config:
      enabled: true
      server:
        native:
          search-locations: classpath:/config/native #本地配置地址

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    ip-address: true